export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  NOT_TRIP_MEMBER: 'NOT_TRIP_MEMBER',
  ALREADY_TRIP_MEMBER: 'ALREADY_TRIP_MEMBER',
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  EXPENSE_AMOUNT_INVALID: 'EXPENSE_AMOUNT_INVALID',
  EXPENSE_PARTICIPANTS_REQUIRED: 'EXPENSE_PARTICIPANTS_REQUIRED',
  PAYER_NOT_MEMBER: 'PAYER_NOT_MEMBER',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;
